---
- name: AAP Demo
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: "{{ message if message is defined else 'Hello World!' }}"
...
