---
- name: Set platform/version specific variables
  include_tasks: tasks/set_vars.yml

- name: Perform platform/version specific tasks
  include_tasks: "{{ lookup('first_found', __demo_role_ff_params) }}"
  vars:
    __demo_role_ff_params:
      files:
        - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
        - "{{ ansible_facts['system'] }}.yml"
        - "default.yml"
      paths:
        - "{{ role_path }}/tasks/sub_tasks"
